import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Photographic Darkroom Base
        darkroom: {
          950: "#090A0C",
          900: "#0F1013",
          850: "#14161A",
          800: "#1B1D23",
          750: "#23262E",
          700: "#2D313B",
          600: "#3D424F",
          500: "#5A6173",
        },
        // Studio Cinnabar Vermillion (Distinctive warm photographic accent)
        cinnabar: {
          50: "#FFF5F3",
          100: "#FFEBE6",
          200: "#FFD6CC",
          300: "#FFB09E",
          400: "#FF755B",
          500: "#FF4D36",
          600: "#E63A23",
          700: "#BF2916",
          800: "#992112",
          900: "#7A1C10",
        },
        // Photographic Amber / Golden Hour
        film: {
          amber: "#F59E0B",
          gold: "#D97706",
          glow: "rgba(245, 158, 11, 0.12)",
        },
        // UI Tokens
        background: "#090A0C",
        foreground: "#E2E4EC",
        surface: "#0F1013",
        "surface-dim": "#090A0C",
        "surface-bright": "#2D313B",
        "surface-container-lowest": "#07080A",
        "surface-container-low": "#121418",
        "surface-container": "#17191F",
        "surface-container-high": "#1E2028",
        "surface-container-highest": "#282B35",
        "surface-variant": "#282B35",
        "on-surface": "#E2E4EC",
        "on-surface-variant": "#C8CBD6",
        "inverse-surface": "#E2E4EC",
        "inverse-on-surface": "#23262E",
        outline: "#3A3F4D",
        "outline-variant": "#252832",
        "surface-tint": "#FF4D36",
        primary: "#FF4D36",
        "on-primary": "#FFFFFF",
        "primary-container": "#E63A23",
        "on-primary-container": "#FFFFFF",
        "inverse-primary": "#FF755B",
        "primary-fixed": "#FFD6CC",
        "primary-fixed-dim": "#FFB09E",
        secondary: "#F59E0B",
        "on-secondary": "#1A1002",
        "secondary-container": "#8C5500",
        "on-secondary-container": "#FFE8C2",
        "secondary-fixed": "#FFE8C2",
        "secondary-fixed-dim": "#FBBF24",
        tertiary: "#22D3EE",
        "on-tertiary": "#002026",
        "tertiary-container": "#0891B2",
        "on-tertiary-container": "#CFFAFE",
        "tertiary-fixed": "#CFFAFE",
        "tertiary-fixed-dim": "#67E8F9",
        error: "#FF6B6B",
        "on-error": "#4A0002",
        "error-container": "#7A0A10",
        "on-error-container": "#FFD6D6",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.25rem",
        gutter: "1.25rem",
        margin: "1.75rem",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
    },
  },
  plugins: [],
};
export default config;
